crash where there are extra commas
Turns out Google Chrome's Title will be whatever a webpage uses, as well as some information about the user. 
```
>>> import pywinctl as pwc
>>> win = pwc.getWindowsWithTitle('Cable and Satellite Tools - Distributor of Tools for CATV, Satellite, Home Theater, Security, Telecom - Google Chrome - Name (Person 1)')
>>> win[0].activate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/share/virtualenvs/lib/python3.9/site-packages/pywinctl/_pywinctl_macos.py", line 725, in activate
    return self.isActive
  File ".local/share/virtualenvs/lib/python3.9/site-packages/pywinctl/_pywinctl_macos.py", line 1094, in isActive
    active = getActiveWindow()
  File ".local/share/virtualenvs/lib/python3.9/site-packages/pywinctl/_pywinctl_macos.py", line 83, in getActiveWindow
    appName, title = ret.replace("\n", "").split(", ")
ValueError: too many values to unpack (expected 2)
```
The above code change fixes this.